In [124]:
import numpy as np

#np.array
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [63]:
#2D 
a = np.array([[1,2,3],[4,5,6]])
print(a)

# 3D
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)


[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [64]:
#dtype
a = np.array([1, 2, 3, 4, 5],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [65]:
# np.arange
np.arange(1,11)
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [66]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [67]:
# np.ones  and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
# np.random

np.random.random((2,3))

array([[0.76505329, 0.09858836, 0.10272295],
       [0.13339387, 0.73136723, 0.00894525]])

In [70]:
# np.linspace
np.linspace(-2,2,6)  #(lower_range , upper_range , no. of items)

array([-2. , -1.2, -0.4,  0.4,  1.2,  2. ])

In [71]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [72]:
# ndim     no.of dimension
c = np.array([[1,2,3],[4,5,6]])
print(c)
a1 =np .arange(10)
a2 =np.arange(12,dtype=float).reshape(3,4)
a3 =np.arange(8).reshape(2,2,2)

# a.ndim
# a1.ndim
a2.ndim
# a3.ndim


[[1 2 3]
 [4 5 6]]


2

In [73]:
# shape
a2.shape

(3, 4)

In [74]:
# size      =>  total item
a3.size

8

In [75]:
#item size
a1.itemsize

4

In [76]:
#dtype
print(a1.dtype)
print(a2.dtype)

int32
float64


In [77]:
# changing  datatype
# astype

a3.astype(np.int32)
# a3.dtype

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [78]:
a1 =np .arange(12).reshape(3,4)
a2 =np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [79]:
# scelar operations
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [80]:
a1>25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [81]:
# vector operations
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [82]:
# Array Functions
a1 =np.random.random((3,3))
a1= np.round(a1*100)
a1

array([[ 2., 95., 61.],
       [23., 21., 84.],
       [52., 93., 20.]])

In [83]:
# max / min / sum /prod
np.max(a1) 

95.0

In [84]:
# 0-> col    1 -> row

np.sum(a1,axis=0)

array([ 77., 209., 165.])

In [85]:
# mean /median /std. / var

np.mean(a1,axis=1)

array([52.66666667, 42.66666667, 55.        ])

In [86]:
# trigonametric function
np.sin (a1)

array([[ 0.90929743,  0.68326171, -0.96611777],
       [-0.8462204 ,  0.83665564,  0.73319032],
       [ 0.98662759, -0.94828214,  0.91294525]])

In [87]:
# dot product
a =np .arange(12).reshape(3,4)
b =np.arange(12,24).reshape(4,3)
np.dot(a,b)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [88]:
# log  and exponents

np.exp(a1)

array([[7.38905610e+00, 1.81123908e+41, 3.10429794e+26],
       [9.74480345e+09, 1.31881573e+09, 3.02507732e+36],
       [3.83100800e+22, 2.45124554e+40, 4.85165195e+08]])

In [89]:
# round /floor  / cell
np.floor(np.random.random((3,3))*100)


array([[56., 38., 13.],
       [17., 80., 86.],
       [71., 31., 45.]])

In [90]:
# indexing and slicing

a =np .arange(10)
b =np .arange(12).reshape(3,4)
c =np .arange(8).reshape(2,2,2)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
a[3]

3

In [92]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
b[2,2]

10

In [94]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [95]:
c[1,0,1]

5

In [96]:
# Slicing
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
a[2:5]

array([2, 3, 4])

In [98]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
b[0,:]

array([0, 1, 2, 3])

In [100]:
b[:,2]

array([ 2,  6, 10])

In [101]:
b[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [102]:
b[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [103]:
b[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [104]:
b[1,::3]

array([4, 7])

In [105]:
c =np .arange(27).reshape(3,3,3)
c


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [106]:
c[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [107]:
c[0,1,:]

array([3, 4, 5])

In [108]:
c[1,:,1]

array([10, 13, 16])

In [109]:
c[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [110]:
for i in a :
    print(i)

0
1
2
3
4
5
6
7
8
9


In [111]:
for i in b:
    print (i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [112]:
for i in c:
    print (i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [113]:
for i in np.nditer(c):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [114]:
# Transpose
np.transpose(a2)

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [115]:
a2.T

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [116]:
# ravel  // give 1 D array for any dimension
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [117]:
# Stacking 

# horizontal
b1 =np .arange(12).reshape(3,4)
b2 =np .arange(12,24).reshape(3,4)
np.hstack((b1,b2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [118]:
# Vertical
np.vstack((b1,b2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [119]:
#Splitting
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [120]:
# hsplit
np.hsplit(b2,2)

[array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [121]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
np.vsplit(b2,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]