In [1]:
# np.sort

import numpy as np
a = np.random.randint(1,100,25)
a

array([15, 23, 74, 30, 52, 31, 64, 93, 69, 69, 90, 67,  6, 24, 83, 21, 20,
       83, 37, 12,  6, 72, 37, 94, 23])

In [2]:
b=np.random .randint(1,100,24).reshape(6,4)
b

array([[13,  4, 74, 77],
       [50, 66, 61, 32],
       [50, 17,  8, 43],
       [79, 87, 79, 80],
       [ 9,  5, 92, 92],
       [21, 33, 74, 68]])

In [3]:
np.sort(a)

array([ 6,  6, 12, 15, 20, 21, 23, 23, 24, 30, 31, 37, 37, 52, 64, 67, 69,
       69, 72, 74, 83, 83, 90, 93, 94])

In [4]:
np.sort(b)

array([[ 4, 13, 74, 77],
       [32, 50, 61, 66],
       [ 8, 17, 43, 50],
       [79, 79, 80, 87],
       [ 5,  9, 92, 92],
       [21, 33, 68, 74]])

In [5]:
np.sort(b,axis=0) # 0 for sort column // 1 for sort row

array([[ 9,  4,  8, 32],
       [13,  5, 61, 43],
       [21, 17, 74, 68],
       [50, 33, 74, 77],
       [50, 66, 79, 80],
       [79, 87, 92, 92]])

In [6]:
# np.append

np.append(a,200)

array([ 15,  23,  74,  30,  52,  31,  64,  93,  69,  69,  90,  67,   6,
        24,  83,  21,  20,  83,  37,  12,   6,  72,  37,  94,  23, 200])

In [7]:
# np.concatenate
# np.unique
# np.expand_dims
a.shape
np.expand_dims(a,axis=0).shape

(1, 25)

In [8]:
np.expand_dims(a,axis=1)

array([[15],
       [23],
       [74],
       [30],
       [52],
       [31],
       [64],
       [93],
       [69],
       [69],
       [90],
       [67],
       [ 6],
       [24],
       [83],
       [21],
       [20],
       [83],
       [37],
       [12],
       [ 6],
       [72],
       [37],
       [94],
       [23]])

In [11]:
# np.where
# np.where(a>50,true,false)
np.where(a>50,0,a)


array([15, 23,  0, 30,  0, 31,  0,  0,  0,  0,  0,  0,  6, 24,  0, 21, 20,
        0, 37, 12,  6,  0, 37,  0, 23])

In [13]:
a
# np.argmax

array([15, 23, 74, 30, 52, 31, 64, 93, 69, 69, 90, 67,  6, 24, 83, 21, 20,
       83, 37, 12,  6, 72, 37, 94, 23])

In [14]:
np.argmax(a)

23

In [15]:
np.argmin(a)

12

In [18]:
#np.cumsum
print(a)
np.cumsum(a)

[15 23 74 30 52 31 64 93 69 69 90 67  6 24 83 21 20 83 37 12  6 72 37 94
 23]


array([  15,   38,  112,  142,  194,  225,  289,  382,  451,  520,  610,
        677,  683,  707,  790,  811,  831,  914,  951,  963,  969, 1041,
       1078, 1172, 1195])

In [19]:
#np.cumprod
np.cumprod(a)

array([         15,         345,       25530,      765900,    39826800,
        1234630800,  1706959872,  -166521856,  1394893824,  1758393344,
        -658388992, -1162389504,  1615597568,   119635968,  1339850752,
       -1927905280,    96600064,  -572129280,   306053120,  -622329856,
         560988160,  1736441856,  -176160768,   620756992,  1392508928])

In [23]:
# np.percentile
print(a)
print(np.percentile(a,100))
print(np.percentile(a,50))
print(np.percentile(a,0))


[15 23 74 30 52 31 64 93 69 69 90 67  6 24 83 21 20 83 37 12  6 72 37 94
 23]
94.0
37.0
6.0


In [27]:
# np.histogram
print(a)
print(np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100]))

[15 23 74 30 52 31 64 93 69 69 90 67  6 24 83 21 20 83 37 12  6 72 37 94
 23]
(array([2, 2, 5, 4, 0, 1, 4, 2, 2, 3], dtype=int64), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


In [28]:
# np.corrcoef       //corelation coefficient

In [29]:
# np.isin
item=[5,6,32,24]
np.isin(a,item)

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False])

In [30]:
# np.flip
np.flip(a)

array([23, 94, 37, 72,  6, 12, 37, 83, 20, 21, 83, 24,  6, 67, 90, 69, 69,
       93, 64, 31, 52, 30, 74, 23, 15])

In [31]:
np.flip (b)

array([[68, 74, 33, 21],
       [92, 92,  5,  9],
       [80, 79, 87, 79],
       [43,  8, 17, 50],
       [32, 61, 66, 50],
       [77, 74,  4, 13]])

In [32]:
# np.put
np.put(a,[0,1],[100,200])
a

array([100, 200,  74,  30,  52,  31,  64,  93,  69,  69,  90,  67,   6,
        24,  83,  21,  20,  83,  37,  12,   6,  72,  37,  94,  23])

In [33]:
# np.delete
np.delete(a,[0,1])

array([74, 30, 52, 31, 64, 93, 69, 69, 90, 67,  6, 24, 83, 21, 20, 83, 37,
       12,  6, 72, 37, 94, 23])

In [34]:
# np.union1d
# np.intersect1d
# np.setdiff1d
# np.setxor1d
# np.in1d

In [38]:
#np.clip
print(a)
np.clip(a,a_min=25,a_max=75)

[100 200  74  30  52  31  64  93  69  69  90  67   6  24  83  21  20  83
  37  12   6  72  37  94  23]


array([75, 75, 74, 30, 52, 31, 64, 75, 69, 69, 75, 67, 25, 25, 75, 25, 25,
       75, 37, 25, 25, 72, 37, 75, 25])

In [36]:
# np.swapaxes
# np.uniform
# np.count_nonzero
# np.count_nonzero
# np.title
# np.repeat
# np.altclose 
# np.equals